In [30]:
from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Dict, Optional, Tuple

import pandas as pd
import pyodbc

In [31]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [32]:
from data_fetcher import RecOpsData

In [33]:
# initialize state of data fetcher
data_fetcher = RecOpsData()
data_fetcher.initialize_state()

C:\Users\SW6720\Github\ec_ops\data_fetcher.py:139: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  self.pos_df = pd.read_sql(self.pos_query, conn)
C:\Users\SW6720\Github\ec_ops\data_fetcher.py:140: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  self.pnl_df = pd.read_sql(self.pnl_query, conn)
C:\Users\SW6720\Github\ec_ops\data_fetcher.py:241: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  self.pos_level_pnl = pd.read_sql(query, conn)

In [28]:
# export for PJM pnl worksheet
filt = data_fetcher.pos_df['ISO'] == 'PJM'
data_fetcher.pos_df[filt].drop(columns="risk_cat").to_csv("K:/Team Folders/Trading/REC Trading/curve/export/pjm_npv.csv")
filt = data_fetcher.pos_df['ISO'] == 'NEPOOL'
data_fetcher.pos_df[filt].drop(columns="risk_cat").to_csv("K:/Team Folders/Trading/REC Trading/curve/export/nepool_npv.csv")

In [29]:
data_fetcher.pos_df.to_clipboard()#to_csv("K:/Team Folders/Trading/REC Trading/curve/export/all_pos_npv.csv")

In [7]:
data_fetcher.pos_df['SOURCE'].value_counts()

SOURCE
-             6689
WIND          3641
SOLAR         2861
CP             964
WIND/SOLAR     109
HYDRO           17
Name: count, dtype: int64

In [16]:
filt = data_fetcher.pos_df['ISO'] == 'PJM'
data_fetcher.pos_df[filt].drop(columns="risk_cat").columns

Index(['AS_OF_DATE', 'TRADE_TYPE', 'BOOK', 'TRADE_BS', 'DMO', 'YEAR', 'ZKEY',
       'ACTIVITY_TYPE', 'TNUM_XREF', 'PROFILE', 'COMMODITY', 'MARKET', 'CPTY',
       'LATEST', 'MKT_PRICE', 'DELTA', 'DELTA_ND', 'MAPPING', 'CONTRACT',
       'STATE', 'ISO', 'TYPE', 'CRS', 'SOURCE', 'MAPPING_CURVE'],
      dtype='object')

In [13]:
data_fetcher.pos_df.to_clipboard()

In [14]:
filt =  (data_fetcher.pos_df['SOURCE']!='CP')

In [72]:
data_fetcher.pnl_df.to_clipboard()

In [26]:
data_fetcher.pos_df.to_clipboard()

In [15]:
df = data_fetcher.pos_df[filt]

In [19]:
data_fetcher.pos_df.to_clipboard()

In [16]:
df.pivot_table(index = 'ISO',columns = 'YEAR')

TypeError: agg function failed [how->mean,dtype->object]

In [6]:
data_fetcher.pos_df.head()

,AS_OF_DATE,TRADE_TYPE,BOOK,TRADE_BS,DMO,YEAR,ZKEY,ACTIVITY_TYPE,TNUM_XREF,PROFILE,...,MKT_PRICE,DELTA,DELTA_ND,MAPPING,CONTRACT,STATE,ISO,TYPE,CRS,SOURCE
0,2026-04-15,ALLOWANCE PHYSICAL,HPLU,B,2028-08-01,2028,154302094.0,None,A65014,OFF PEAK,...,2.46,28884.605234,31452.16,TX_SOLAR (CRS-LISTED) FH,OTC,TX,ERCOT,FH,CRS,SOLAR
1,2026-04-15,ALLOWANCE PHYSICAL,HPLU,B,2028-11-01,2028,154302096.0,None,A65014,OFF PEAK,...,2.56,30800.601311,33829.72,TX_SOLAR (CRS-LISTED) BH,OTC,TX,ERCOT,BH,CRS,SOLAR
2,2026-04-15,ALLOWANCE PHYSICAL,HPLU,B,2029-02-01,2028,154302098.0,None,A65014,OFF PEAK,...,2.56,17905.372386,19834.13,TX_SOLAR (CRS-LISTED) BH,OTC,TX,ERCOT,BH,CRS,SOLAR
3,2026-04-15,ALLOWANCE PHYSICAL,HPLU,B,2029-05-01,2029,154302100.0,None,A65014,OFF PEAK,...,2.66,18384.940071,20546.92,TX_SOLAR (CRS-LISTED) FH,OTC,TX,ERCOT,FH,CRS,SOLAR
4,2026-04-15,ALLOWANCE PHYSICAL,HPLU,B,2029-08-01,2029,154302102.0,None,A65014,OFF PEAK,...,2.66,27890.701691,31452.16,TX_SOLAR (CRS-LISTED) FH,OTC,TX,ERCOT,FH,CRS,SOLAR

In [17]:
# export for Voluntary pnl worksheet

vol_regions = ['ERCOT','NATIONAL','SPP','MISO','NORTH AMERICA']
filt = data_fetcher.pos_df['ISO'].apply(lambda x: x in vol_regions) & (data_fetcher.pos_df["YEAR"] >2024)
data_fetcher.pos_df[filt].to_clipboard()

In [8]:
data_fetcher.pos_df['ISO'].value_counts()

ISO
ERCOT            6298
PJM              3794
NEPOOL           1772
NATIONAL          717
NYISO             171
SPP                30
MISO                3
NORTH AMERICA       2
Name: count, dtype: int64

In [28]:
data_fetcher.pos_df.to_clipboard()

In [17]:
delivs_sql_path = "./sql/deliv_excel.sql"
with open(delivs_sql_path, "r", encoding="utf-8") as f:
            delivs_sql = f.read()

bstamp_sql_path = "./sql/deliv_excel_bstamp.sql"
with open(bstamp_sql_path, "r", encoding="utf-8") as f:
            bstamp_sql = f.read()

In [7]:
tmac_sql_path = "./sql/tmac.sql"
with open(tmac_sql_path, "r", encoding="utf-8") as f:
            tmac_sql = f.read()

In [8]:
tmac_df = data_fetcher.execute_znet_query(tmac_sql)

C:\Users\SW6720\Github\ec_ops\data_fetcher.py:121: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [9]:
tmac_df.to_csv("K:/Team Folders/Trading/REC Trading/tmac.csv")

In [20]:
cdh_sql_path = "./sql/victor_query_cdh.sql"
with open(cdh_sql_path, "r", encoding="utf-8") as f:
            cdh_sql = f.read()
cdh_pos = data_fetcher.execute_mssql_query(cdh_sql)

C:\Users\SW6720\Github\ec_ops\data_fetcher.py:129: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

RuntimeError: Failed to execute SQL on MSSQL: Execution failed on sql 'SELECT
    cpty,
    COUNT(*) AS legs,
    SUM(deltand) AS sum_delta_nd
FROM "cdh_eemnapowertradingdata_32020"."greeks_aligne_n_ot"
WHERE asofdate = TIMESTAMP '2026-05-05 00:00:00'
  AND active = true
  AND book = 'TREC'
  AND mrktcattr1 = 'REC'
  AND sourcesystem = 'Aligne'
  AND TRY_CAST(RTRIM(comp) AS INTEGER) = 2026
GROUP BY cpty
ORDER BY ABS(SUM(deltand)) DESC;': ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '2026-05-05 00:00:00'. (102) (SQLExecDirectW)")

In [16]:
aligne_sql_path = "./sql/victor_query_aligne.sql"
with open(aligne_sql_path, "r", encoding="utf-8") as f:
            aligne_sql = f.read()
aligne_pos = data_fetcher.execute_znet_query(aligne_sql)

C:\Users\SW6720\Github\ec_ops\data_fetcher.py:121: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [18]:
aligne_pos.to_clipboard()

In [13]:
cdh_pos.to_clipboard()

In [59]:
tmac_df.to_clipboard()

In [60]:
tmac_df.to_c

,REPORT_DATE,TRADE_DATE,BOOK,ZKEY,XREF,B_S,MARKET,YEAR,AMOUNT,TRADE_PRICE,DEL_DATE
0,2026-04-28,2026-04-16,TMAC,155527221.0,SMU0094,B,CTC3,2027,10000.0,28.25,2027-12-01
1,2026-04-28,2026-04-20,TMAC,155570123.0,SMU0099,B,PAT2,2026,70000.0,22.75,2026-05-20
2,2026-04-28,2026-04-21,TMAC,155593814.0,SMU0108,B,MAAPS,2026,10000.0,18.00,2027-06-01
3,2026-04-28,2026-04-21,TMAC,155589406.0,SMU0103,B,USSOFH,2027,150000.0,2.15,2027-06-30
4,2026-04-28,2026-04-21,TMAC,155611766.0,SMU0110,B,TXWIBH,2029,50000.0,2.90,2030-03-15

In [15]:
delivs_df = data_fetcher.execute_znet_query(delivs_sql)
bstamp_df = data_fetcher.execute_znet_query(bstamp_sql)

C:\Users\SW6720\Github\ec_ops\data_fetcher.py:121: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
C:\Users\SW6720\Github\ec_ops\data_fetcher.py:121: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [11]:
delivs_df.to_clipboard()

In [18]:
print(delivs_df.shape)
delivs_df.columns

(0, 23)

Index(['REPORT_DATE', 'DMO', 'TRADE_TYPE2', 'TNUM_XREF', 'TNUMGROUP',
       'GROUP_DSC2', 'TRADER_NAME', 'BOOK', 'TRADE_BS', 'ZKEY', 'TRADE_DATE',
       'C19_CPTY', 'CPTY_DESCR', 'STRIKE', 'TRADE_PRICE', 'MKT', 'YEAR',
       'LOCATION_DESCR', 'STATFULL', 'DEL_DATEEND', 'AMOUNT', '4STAMP',
       'MEMO'],
      dtype='object')

In [20]:
delivs_df.merge(bstamp_df, on ='TNUM_XREF', how = 'left',suffixes=('',"_b")).to_clipboard()

In [25]:
our_books = ['HNAT','HNEP','HNYK','HPJR','HREC','TREC','HPHM']

filt = (delivs_df['BOOK'].apply(lambda x: x in our_books)) & (delivs_df['C19_CPTY'].apply(lambda x: x not in our_books))
delivs_df[filt].to_clipboard()

In [53]:
current_day_query = """select * from tracrisk.ENGIE_POSITION_RT_ENRICHED

WHERE BOOK = 'HREC'

and datestart > tracrisk.NEXT_BUSINESS_DAY(trunc(sysdate))
"""

In [55]:
data_fetcher.execute_znet_query(current_day_query).to_clipboard()

C:\Users\SW6720\Github\ec_ops\data_fetcher.py:121: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [34]:
date_pnl_sql_path = "./sql/eemna_pnl_date.sql"
with open(date_pnl_sql_path, "r", encoding="utf-8") as f:
            pnl_date_sql = f.read()
pnl_date = data_fetcher.execute_mssql_query(pnl_date_sql)

C:\Users\SW6720\Github\ec_ops\data_fetcher.py:129: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [35]:
pnl_date.head()

,AS_OF_DATE,BOOK_ATTR4,BOOK_ATTR6,BOOK_ATTR7,BOOK_ACCTSUB4,CPTY,BOOK,MARKET,YEAR,TRADER,...,PL_VOIDTRADE_NPV,PL_INCEP_NPV_NET_C,PL_OTHER,PL_INCEP_NPV,PL_FEE,PL_RESERVE,PL_COMMISSION,NOTIONAL_QTY,ATTRIBUTE,LATEST
0,2026-05-01,ERC_REC_LT,,POWERDESK,,HREC,HPLU,TXGSBH,2031,NAD,...,0.0,-140981.220579,-2.182787e-11,-140981.220579,0.0,0.0,0.0,-53663.85,REC,YES
1,2026-05-01,ERC_REC_LT,,POWERDESK,,HREC,HPLU,TXGSFH,2030,NAD,...,0.0,-133355.241028,2.910383e-11,-133355.241028,0.0,0.0,0.0,-51999.08,REC,YES
2,2026-05-01,ERC_REC_LT,,POWERDESK,,HREC,HPLU,TXGSFH,2037,NAD,...,0.0,-139550.707355,7.275958e-12,-139550.707355,0.0,0.0,0.0,-51999.08,REC,YES
3,2026-05-01,ERC_REC_LT,,POWERDESK,,OBJJ,HPLU,TXGSBH,2031,NAD,...,0.0,140981.220579,2.182787e-11,140981.220579,0.0,0.0,0.0,53663.85,REC,YES
4,2026-05-01,ERC_REC_LT,,POWERDESK,,OBJJ,HPLU,TXGSFH,2030,NAD,...,0.0,133355.241028,-2.910383e-11,133355.241028,0.0,0.0,0.0,51999.08,REC,YES

In [26]:
filt = (pnl_date['YEAR']=='2026') & ((pnl_date['MARKET']=='CCXPA2') | (pnl_date['MARKET']=='PAT2'))
pnl_date[filt][['AS_OF_DATE','PL_DAILY']]


pivot_df = (
    pnl_date[filt].pivot_table(index='AS_OF_DATE', columns=['MARKET','YEAR'], values=['PL_DAILY','NOTIONAL_QTY'], aggfunc='sum', fill_value=0
    )
    .reset_index()
)

pivot_df.to_csv("./output/pa2_26_july_issues_2.csv")

In [28]:
pnl_date['month']=pnl_date['AS_OF_DATE'].apply(lambda x: x.month)

In [33]:
pnl_date.to_clipboard()

In [34]:
pivot_df = (
    pnl_date.pivot_table(index='month', columns=['MARKET'], values=['PL_DAILY_NPV'], aggfunc='sum', fill_value=0
    )
    .reset_index()
)
pivot_df.transpose().to_clipboard()

In [56]:
hrec_pnl_sql_path = "./sql/scratch/hrec_pnl copy.sql"
with open(hrec_pnl_sql_path, "r", encoding="utf-8") as f:
            pnl_hrec_sql = f.read()
pnl_hrec = data_fetcher.execute_mssql_query(pnl_hrec_sql)

C:\Users\SW6720\Github\ec_ops\data_fetcher.py:129: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [7]:
pnl_hrec

,AS_OF_DATE,BOOK_ATTR4,BOOK_ATTR6,BOOK_ATTR7,BOOK_ACCTSUB4,CPTY,BOOK,MARKET,YEAR,TRADER,...,PL_VOIDTRADE_NPV,PL_INCEP_NPV_NET_C,PL_OTHER,PL_INCEP_NPV,PL_FEE,PL_RESERVE,PL_COMMISSION,NOTIONAL_QTY,ATTRIBUTE,LATEST
0,2026-06-02,ERC_REC_LT,,POWERDESK,WAREHOUSING,BNPCBROKER,HREC,CCXTGB,2025,SMU,...,0.0,0.000000,0.000000e+00,0.000000,0.0,0.0,0.0,38000.00,REC,YES
1,2026-06-02,ERC_REC_LT,,POWERDESK,WAREHOUSING,BNPCBROKER,HREC,CCXTSB,2023,HMI2,...,0.0,-147500.000000,0.000000e+00,-147500.000000,0.0,0.0,0.0,50000.00,REC,YES
2,2026-06-02,ERC_REC_LT,,POWERDESK,WAREHOUSING,BNPCBROKER,HREC,CCXTSB,2024,HMI2,...,0.0,-145000.000000,0.000000e+00,-145000.000000,0.0,0.0,0.0,50000.00,REC,YES
3,2026-06-02,ERC_REC_LT,,POWERDESK,WAREHOUSING,BNPCBROKER,HREC,CCXTSB,2024,HMI2,...,0.0,-12500.000000,0.000000e+00,-12500.000000,0.0,0.0,0.0,-50000.00,REC,YES
4,2026-06-02,ERC_REC_LT,,POWERDESK,WAREHOUSING,BNPCBROKER,HREC,TXWIFH,2025,AST,...,0.0,16650.000000,0.000000e+00,16650.000000,0.0,0.0,0.0,-37000.00,REC,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43349,2026-08-03,ERC_REC_LT,,POWERDESK,WAREHOUSING,TREC,HREC,TXWIBH,2027,HMI2,...,0.0,-181056.500602,2.037268e-10,-181056.500602,0.0,0.0,0.0,75000.00,REC,YES
43350,2026-08-03,ERC_REC_LT,,POWERDESK,WAREHOUSING,TREC,HREC,TXWIFH,2025,HMI2,...,0.0,-137500.000000,0.000000e+00,-137500.000000,0.0,0.0,0.0,0.00,REC,YES
43351,2026-08-03,ERC_REC_LT,,POWERDESK,WAREHOUSING,TREC,HREC,TXWIFH,2032,HMI2,...,0.0,-206847.785326,-7.275958e-10,-206847.785326,0.0,0.0,0.0,156789.00,REC,YES
43352,2026-08-03,ERC_REC_LT,,POWERDESK,WAREHOUSING,VITOLINC,HREC,TXWIFH,2027,HMI2,...,0.0,947324.466154,5.820766e-10,947324.466154,0.0,0.0,0.0,-400000.00,REC,YES
43353,2026-08-03,ERC_REC_LT,,POWERDESK,WAREHOUSING,VPRW,HREC,TXWABH,2028,NAD,...,0.0,-687289.237027,1.746230e-10,-687289.237027,0.0,0.0,0.0,320521.39,REC,YES

In [57]:
pnl_hrec.to_clipboard()